### ISSUE TITLE
question: a Pull Request

### ISSUE THREAD

**Issue by armand1m** [drone-demos/drone-with-nodejs#2]
Actually this repository is empty and I don't know why. Leaving that behind, do you guys accept pull requests? I have a tested nodejs webservice built using hapi.js  and I've used drone for building and deploying it. I can do a little hello world example and push it as a pull request.

**Comment by YongX** [comment]
Hi there, can you make a pull request? I'm looking for the example.

**Comment by jamrizzi** [comment]
Is there a reason this repo is empty???

**Comment by armand1m** [comment]
#3 tackles tihs

**Comment by armand1m** [comment]
this can be closed now
